#!/usr/bin/env python3
"""Normalize SeqQA completion datasets into the processed grading schema."""

# Usage example:
# uv run --directory data python seqqa/process_completions.py \
#     --source-repo hf-carbon/seqqa-sft-v1_gemma-4-31B-it
#
# This processes SeqQA completion data generated by Datatrove and reshapes it
# for data/seqqa/grade_completions.py.

import argparse
import logging
from typing import Any

from datasets import Dataset, load_dataset

logger = logging.getLogger(__name__)

PROCESSED_COLUMN_ORDER = (
    "id",
    "question",
    "ideal",
    "prompt_suffix",
    "prompt",
    "subtask",
    "source",
    "validator_type",
    "validator_params",
    "answer_regex",
    "question_len",
    "ideal_len",
    "messages",
    "model_completion",
    "model_completion_tokens",
    "model_finish_reason",
)

PROCESSED_CONFIG = "processed"
PROCESSED_SPLIT = "train"


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Load a SeqQA completion dataset, rename the Datatrove `text` "
            "column to `prompt`, expand `rollout_results`, and optionally "
            "push the processed subset back to the same dataset repo."
        )
    )
    parser.add_argument(
        "--source-repo",
        required=True,
        help="Source dataset repo id.",
    )
    parser.add_argument(
        "--source-config",
        help="Optional source config to read. If omitted, load the dataset default.",
    )
    parser.add_argument(
        "--source-split",
        default="train",
        help="Source split to read (default: train).",
    )
    parser.add_argument(
        "--push",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Push the processed subset to the same source dataset repo (default: enabled).",
    )
    return parser.parse_args()


def resolve_source_config(args: argparse.Namespace, dataset: Dataset) -> str:
    """Resolve the source config name used for metadata."""
    if args.source_config is not None:
        return args.source_config
    dataset_info = getattr(dataset, "info", None)
    return str(getattr(dataset_info, "config_name", "") or "")


def load_source_dataset(args: argparse.Namespace) -> Dataset:
    """Load the source dataset with or without an explicit config."""
    if args.source_config is None:
        return load_dataset(args.source_repo, split=args.source_split)
    return load_dataset(
        args.source_repo,
        args.source_config,
        split=args.source_split,
    )


def _normalize_rollout_result(row: dict[str, Any]) -> dict[str, Any]:
    rollout_results = row.get("rollout_results")
    return rollout_results[0]


def _normalize_usage(rollout: dict[str, Any]) -> dict[str, Any]:
    usage = rollout.get("usage")
    if usage is None:
        return {}
    if not isinstance(usage, dict):
        raise ValueError("Expected rollout usage metadata to be a mapping.")
    return usage


def has_rollout_results(row: dict[str, Any]) -> bool:
    """Keep only rows with at least one rollout result."""
    return bool(row.get("rollout_results"))


def has_stop_finish_reason(row: dict[str, Any]) -> bool:
    """Keep only rows where the model completed normally."""
    return row.get("model_finish_reason") == "stop"


def process_row(
    row: dict[str, Any],
) -> dict[str, Any]:
    """Transform one raw completion row into the processed grading schema."""
    rollout = _normalize_rollout_result(row)
    usage = _normalize_usage(rollout)

    question = str(row["question"])
    ideal = str(row["ideal"])
    prompt_suffix = str(row.get("prompt_suffix") or "")
    prompt = str(row.get("text") or row.get("prompt") or "")
    if not prompt:
        prompt = f"{question}\n\n{prompt_suffix}" if prompt_suffix else question

    processed_row: dict[str, Any] = {
        "id": str(row["id"]),
        "question": question,
        "ideal": ideal,
        "prompt_suffix": prompt_suffix,
        "prompt": prompt,
        "subtask": str(row["subtask"]),
        "source": str(row.get("source") or ""),
        "validator_type": str(row.get("validator_type") or ""),
        "validator_params": row.get("validator_params") or {},
        "answer_regex": str(row.get("answer_regex") or ""),
        "question_len": int(row.get("question_len") or len(question)),
        "ideal_len": int(row.get("ideal_len") or len(ideal)),
        "model_completion": str(rollout.get("text") or ""),
        "model_completion_tokens": usage.get("completion_tokens"),
        "model_finish_reason": rollout.get("finish_reason"),
    }
    processed_row["messages"] = [
        {"role": "user", "content": prompt},
        {"role": "assistant", "content": processed_row["model_completion"]},
    ]

    return processed_row


def process_dataset(dataset):
    """Filter invalid rows and map the remaining ones into processed rows."""
    num_rows = len(dataset)
    dataset = dataset.filter(has_rollout_results, desc="Filtering rows without rollout_results")
    filtered_rows = num_rows - len(dataset)
    if filtered_rows:
        logger.info("Filtered out %d rows without rollout_results", filtered_rows)

    dataset = dataset.map(
        process_row,
        remove_columns=list(dataset.column_names),
        desc="Processing completions",
    )
    num_rows = len(dataset)
    dataset = dataset.filter(
        has_stop_finish_reason,
        desc="Filtering rows without stop finish_reason",
    )
    filtered_rows = num_rows - len(dataset)
    if filtered_rows:
        logger.info("Filtered out %d rows without stop finish_reason", filtered_rows)
    return dataset.select_columns(list(PROCESSED_COLUMN_ORDER))


def push_rows(dataset, args: argparse.Namespace) -> None:
    """Push processed rows back to the same source dataset repo."""
    dataset.push_to_hub(
        args.source_repo,
        config_name=PROCESSED_CONFIG,
        split=PROCESSED_SPLIT,
        commit_message=(
            f"Add processed completion subset for "
            f"{args.source_config or 'default'} ({len(dataset)} rows)"
        ),
    )
    logger.info(
        "Pushed %d rows to %s / %s / %s",
        len(dataset),
        args.source_repo,
        PROCESSED_CONFIG,
        PROCESSED_SPLIT,
    )


def run(args: argparse.Namespace) -> int:
    """Execute the processing workflow."""
    dataset = load_source_dataset(args)

    resolved_source_config = resolve_source_config(args, dataset)
    logger.info(
        "Loaded %d rows from %s / %s / %s",
        len(dataset),
        args.source_repo,
        resolved_source_config or "<default>",
        args.source_split,
    )

    processed_dataset = process_dataset(dataset)
    logger.info("Processed %d rows", len(processed_dataset))

    if args.push:
        if not len(processed_dataset):
            logger.error("No processed rows available to push.")
            return 1
        push_rows(processed_dataset, args)
    else:
        print(
            f"Dry run: prepared {len(processed_dataset)} processed rows for "
            f"{args.source_repo} / {PROCESSED_CONFIG} / {PROCESSED_SPLIT}"
        )

    return 0


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    raise SystemExit(run(parse_args()))


if __name__ == "__main__":
    main()
